### ISSUE TITLE
Demo link for membership app is not working

### ISSUE THREAD

**Issue by max-85** [phillip-kruger/membership#2]

**Comment by max-85** [comment]
http://membership-demo.a3c1.starter-us-west-1.openshiftapps.com/membership/ seems to be offline.

**Comment by phillip-kruger** [comment]
Yes, apologies, I'll deploy to another environment soon and update the link

**Comment by phillip-kruger** [comment]
Fix. Please use the link in the README to use the new environment. Thanks for reporting.
